# Generated by Django 3.0.2 on 2020-01-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('activate', models.BooleanField()),
                ('subscription', models.BooleanField()),
            ],
        ),
    ]
